"""Strict lifecycle primitives for the next-generation orchestrator."""

from .core import OrchestratorCore
from .artifact_committer import (
    ARTIFACT_COMMIT_FAILED,
    ARTIFACT_CONSISTENCY_FAILED,
    ArtifactCommitResult,
    ArtifactCommitter,
    ArtifactCompletionEvent,
    ArtifactConsistencyResult,
    ArtifactDiagnostic,
    check_artifact_success_gate,
)
from .budget import ExecutionBudget, ExecutionBudgetExhausted
from .model_gateway import (
    ModelCallActivity,
    ModelCallCancelled,
    ModelCallContext,
    ModelCallTimeout,
    ModelGateway,
    ModelGatewayError,
    ModelStreamDataKind,
)
from .generation_scheduler import (
    FileGenerationContext,
    GeneratedContent,
    GenerationNodeResult,
    GenerationNodeStatus,
    GenerationScheduleResult,
    GenerationScheduleStats,
    GenerationScheduleStatus,
    GenerationScheduler,
)
from .models import (
    OrchestrationCommand,
    OrchestrationResult,
    OrchestrationStage,
    OrchestrationState,
    OrchestrationStatus,
    StageResult,
)
from .plan import (
    FilePlanValidationError,
    GenerationPlan,
    PlanFileOrigin,
    PlanIssue,
    PlanPolicy,
    PlannedFile,
    build_file_plan,
    normalize_plan_path,
)
from .state_machine import (
    InvalidOrchestrationTransition,
    OrchestrationRevisionConflict,
    advance_state,
    terminate_state,
)
from .store import OrchestrationCheckpointStore, OrchestrationStore
from .adapters import AdapterResult, GenerationModeAdapter, GenerationRequest, TraditionalAdapter
from .routing import (
    CORE_ENGINE,
    CORE_ENGINE_VERSION,
    LEGACY_ENGINE,
    LEGACY_ENGINE_VERSION,
    engine_metadata,
    select_engine,
)
from .engine_router import EngineRouteResult, compare_shadow_results, route_generation

__all__ = [
    "ARTIFACT_COMMIT_FAILED",
    "ARTIFACT_CONSISTENCY_FAILED",
    "ArtifactCommitResult",
    "ArtifactCommitter",
    "ArtifactCompletionEvent",
    "ArtifactConsistencyResult",
    "ArtifactDiagnostic",
    "InvalidOrchestrationTransition",
    "ExecutionBudget",
    "ExecutionBudgetExhausted",
    "FilePlanValidationError",
    "GenerationPlan",
    "FileGenerationContext",
    "GeneratedContent",
    "GenerationNodeResult",
    "GenerationNodeStatus",
    "GenerationScheduleResult",
    "GenerationScheduleStats",
    "GenerationScheduleStatus",
    "GenerationScheduler",
    "ModelCallActivity",
    "ModelCallCancelled",
    "ModelCallContext",
    "ModelCallTimeout",
    "ModelGateway",
    "ModelGatewayError",
    "ModelStreamDataKind",
    "OrchestrationCheckpointStore",
    "OrchestrationCommand",
    "OrchestrationResult",
    "OrchestrationRevisionConflict",
    "OrchestrationStage",
    "OrchestrationState",
    "OrchestrationStatus",
    "OrchestrationStore",
    "OrchestratorCore",
    "PlanFileOrigin",
    "PlanIssue",
    "PlanPolicy",
    "PlannedFile",
    "StageResult",
    "advance_state",
    "build_file_plan",
    "check_artifact_success_gate",
    "normalize_plan_path",
    "terminate_state",
    "AdapterResult",
    "GenerationModeAdapter",
    "GenerationRequest",
    "TraditionalAdapter",
    "CORE_ENGINE",
    "CORE_ENGINE_VERSION",
    "LEGACY_ENGINE",
    "LEGACY_ENGINE_VERSION",
    "engine_metadata",
    "select_engine",
    "EngineRouteResult",
    "compare_shadow_results",
    "route_generation",
]
